### ISSUE TITLE
the wgan-gp code is not work

### ISSUE THREAD

**Issue by LDOUBLEV** [handspeaker/gan_practice#1]
there must be some wrong  .   i meet a big problem, when i use the wgan-gp to generate mnist picture..
the d_loss has decreased over -2000,and the g_loss has increased over 1000 after some epoch . can you help me to solve this problem .thanks

**Comment by LDOUBLEV** [comment]
![image](https://user-images.githubusercontent.com/26592129/28754239-30af3446-7574-11e7-8b24-1f27d04e1894.png)

**Comment by handspeaker** [comment]
does the generated images show convergence? If the generated images are like mnist images gradually you can ignore the loss
