### ISSUE TITLE
raise ValueError("Can't load save_path when it is None.")

### ISSUE THREAD

**Issue by yinyanting** [handspeaker/gan_practice#2]
Traceback (most recent call last):
  File "dcgan.py", line 200, in <module>
    infer(args)
  File "dcgan.py", line 168, in infer
    saver.restore(sess, model_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1557, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
yyt@zws-P900:~/wgan/ganPractice/gan_practice$ tensorflow
tensorflow: command not found
yyt@zws-P900:~/wgan/ganPractice/gan_practice$ pip tensorflow

how to define CHECKPOINT_PATH

**Comment by handspeaker** [comment]
> how to define CHECKPOINT_PATH

hi yinyanting，
you can add arg '--model_dir' in command line, the code will automatically choose the latest checkpoint file.
